config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show, :edit, :update]

  get 'bookers/top' => 'bookers#top'
  get 'bookers/about' => 'bookers#about'

  resources :bookers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/users' => 'users#user'

  root 'bookers#top'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booker.rb
class Booker < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :impression, length: {maximum: 200}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:name]

  has_many :bookers
  attachment :profile_image

  validates :name, length: { minimum: 2, maximum: 20}
  validates :profile_text, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for resource
    root_path
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

 	def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  	end

end

app/controllers/bookers_controller.rb
class BookersController < ApplicationController
 before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]

  def top
  end

  def about
  end

  def index
   	@post = Booker.page(params[:page]).reverse_order
    @newpost = Booker.new
    @user = User.all
  end

  def show
    @newpost = Booker.new
  	@post = Booker.find(params[:id])
  end

  def create
    @post = Booker.page(params[:page]).reverse_order
  	@newpost = Booker.new(post_params)
    @newpost.user_id = current_user.id
    if @newpost.save
      redirect_to user_path(current_user.id)
    else
      render action: :index
    end
  end

  def edit
  	@post = Booker.find(params[:id])
  end

  def update
  	post = Booker.find(params[:id])
  	post.update(post_params)
  	redirect_to booker_path
  end

  def destroy
  	post = Booker.find(params[:id])
  	post.destroy
  	redirect_to bookers_path, notice: 'deletion successfully completed.'
  end

  private
  def post_params
  	params.require(:booker).permit(:title, :impression, :user_id)
  end

  def user_params
      params.require(:user).permit(:name, :profile_image, :profile_text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!

  def user
    @user = User.all
    @newpost = Booker.new
  end

  def show
    @user = User.find(params[:id])
    @post = @user.bookers.page(params[:page]).reverse_order
    @newpost = Booker.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

	private
	def user_params
   		params.require(:user).permit(:name, :profile_image, :profile_text)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookers/about.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<h1> about Bookers </h1>
			<h4>under construction... </h4>
		</div>
	</div>
</div>

app/views/bookers/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h2>Edit post</h2>
				<% if @post.user.id == current_user.id %>
					<%= form_for(@post) do |f| %>
						<h4> title </h4>
							<%= f.text_field :title %>
						<h4> impression </h4>
							<%= f.text_area :impression %><br/>
						<%= f.submit '編集完了' ,data: {confirm: 'この内容で更新してよろしいですか?'}, class: 'btn btn-primary' %>
					<% end %>
				<% else %>
					<p> 編集権限がありません </p>
				<% end %>
		</div>
	</div>
</div>

app/views/bookers/index.html.erb
<!doctype html>
<html>
<head>
	<meta charset="UTF-8">
</head>
<!-- body -->
<body>
	<!-- フラッシュメッセージ-->
	<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice] %></p>
	<% end %>
	<!-- 投稿時のエラーメッセージ -->
	<% if @newpost.errors.any? %>
	<div id="error_explanation">
		<h3><%= @newpost.errors.count %>件のエラーが発生しました。</h3>
		<ul>
			<% @newpost.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<!-- ページの中身 -->
	<div class="container">
		<div class="row">
			<!-- ユーザー情報（共通テンプレート） -->
			<%= render 'users/list', newpost: @newpost %>
			<!-- 投稿内容一覧 -->
			<div class="col-xs-9">
				<section class="contents">
					<h3>Books(all posts)</h3>
					<table class="table table-stripped">
						<tr align="left">
							<th> user </th>
							<th> </th>
							<th> title </th>
							<th> impression </th>
							<th></th>
						</tr>
						<% @post.each do |post| %>
						<tr align="left">
							<td> <%= attachment_image_tag post.user, :profile_image, :fill, 45, 45, class: "img-square pull-left profile-thumb", fallback: "no_image.jpg" %></td>
							<td> <%= link_to post.user.name, user_path(post.user_id) %> </td>
							<td> <%= link_to post.title, booker_path(post) %> </td>
							<td> <%= link_to post.impression, booker_path(post) %> </td>
							<td> <%= link_to "show detail", booker_path(post), class: 'btn btn-info' %> </td>
						</tr>
						<% end %>
					</table>
					<%= paginate @post, class: "pagenate" %>
				</section>
			</div>
		</div>
	</div>
</body>
</html>

app/views/bookers/show.html.erb
<!doctype html>
<html>
<div class="container">
	<div class="row">
		<!-- ユーザー情報（共通テンプレート） -->
		<%= render 'users/list', newpost: @newpost %>
		<!-- ページの中身 -->
		<div class="col-xs-9">
			<section class="contents">
				<h3>Post</h3>
				<table class="table table-stripped">
					<tr align="left">
						<th>posted by</th>
						<th>title </th>
						<th>impression  </th>
						<th>posted at </th>
					</tr>
					<tr align="left">
						<td><%= attachment_image_tag @post.user, :profile_image, :fill, 45, 45, class: "img-square pull-left profile-thumb", fallback: "no_image.jpg" %> <br>
							<%= @post.user.name %></td>
							<td><%= @post.title %></td>
							<td><%= @post.impression %></td>
							<td><%= @post.created_at.to_s(:created_at) %></td>
					</tr>
				</table>
				<% if @post.user.id == current_user.id %>
					<%= link_to "編集", edit_booker_path(@post), class: 'btn btn-info'  %>
					<%= link_to "削除", booker_path(@post), method: :delete, data: {confirm: '本当に削除してよろしいですか?'}, class: 'btn btn-danger'  %>
				<% end %>
				<%= link_to "一覧に戻る", bookers_path, class: 'btn btn-success'  %>
			</section>
		</div>
	</div>
</div>
</html>

app/views/bookers/top.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<div class="top-page-text">
				<h1>Welcome to Bookers!</h1>
				<p>"書籍レビュー共有サイト"<br>
				自由に投稿してください・・・</p>
			</div>
			<div class="top-page-button">
				<%=link_to "新規ユーザーの方はこちら(サインアップ)", new_user_registration_path, class: 'col-xs-4 btn btn-info top-page-button' %><br/>
				<%=link_to "登録済みユーザーの方はこちら(ログイン)", new_user_session_path, class: 'col-xs-4 btn btn-danger top-page-button'%>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <!-- ヘッダーメニュー -->
  <div class="header">
   <div id="slidemenu">
    <div class="container">
      <div class="row">
        <div class="title col-xs-4"> <span class="glyphicon glyphicon-book color-white" aria-hidden="true"> </span>Bookers</div>
        <div class="col-xs-8" >
          <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
            <% if user_signed_in? %>
            <li class="top-menu">
              <%= link_to sanitize('<span class="glyphicon glyphicon-home color-white" aria-hidden="true"></span>') + '  Home: My page', user_path(current_user.id) %>
            </li>
            <li class="top-menu">
              <%= link_to sanitize('<span class="glyphicon glyphicon-th-list color-white" aria-hidden="true"></span>')+'  Books', bookers_path %>
            </li>
            <li class="top-menu">
              <%= link_to sanitize('<span class="glyphicon glyphicon-user color-white" aria-hidden="true"></span>') + '  Users', users_path %>
            </li>
            <li class="top-menu">
              <%= link_to sanitize('<span class="glyphicon glyphicon-log-out color-white" aria-hidden="true"></span>') +'  Log out', destroy_user_session_path, method: :delete %>
            </li>
            <% else %>
            <li class="top-menu">
              <%= link_to sanitize('<span class="glyphicon glyphicon-plus color-white" aria-hidden="true"></span>') +'  Sign up', new_user_registration_path %>
            </li>
            <li class="top-menu">
              <%= link_to sanitize('<span class="glyphicon glyphicon-log-in color-white" aria-hidden="true"></span>') +'  Log in', new_user_session_path %>
            </li>
            <li class="top-menu">
              <%= link_to sanitize('<span class="glyphicon glyphicon-minus color-white" aria-hidden="true"></span>') + '  Top', bookers_top_path %>
            </li>
            <li class="top-menu">
              <%= link_to sanitize('<span class="glyphicon glyphicon-tree-conifer color-white" aria-hidden="true"></span>') + '  About', bookers_about_path %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<%= yield %>

<!-- フッター -->
<footer>
  <p> CopyRight Infratop.inc </p>
</footer>

</body>
</html>

app/views/users/_list.html.erb
<!-- 共通テンプレート（ページ左半分） -->
<div class="col-xs-3">
	<!-- 上半分 ユーザー情報-->
	<section class="">
		<h3> Your Profile </h3>
		<img><%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, class: "img-circle pull-left profile-thumb" ,fallback: "no_image.jpg"%></img> <br/>
		<table class="table table-stripped">
			<tr><th> name </th>
				<th><%= current_user.name %></th>
			</tr>
			<tr><th> introduction </th>
				<th><%= current_user.profile_text %></th>
			</tr>
		</table>
		<%= link_to edit_user_path(current_user.id), class: 'col-xs-12 btn btn default' do %>
			<span class= "glyphicon glyphicon-edit"> </span>
		<% end %>
	</section>
	<!-- 下半分 新規投稿フォーム -->
	<section class="new-book">
		<p class="headline-create-new-post"> create new post </p>
		<%= form_for(newpost) do |f| %>
			<h4> title </h4>
				<%= f.text_field :title, class: "input-xlarge" %>
			<h4> impression </h4>
				<%= f.text_area :impression, :size=> "26x5" %><br />
			<%= f.submit 'create!', class: 'btn btn-primary col-xs-12'%>
		<% end %>
	</section>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div class="edit-page-head"></div>
			<%= form_for(@user) do |f| %>
				<label>Name</label><br/>
					<%= f.text_field :name, autofocus: true, class:"imput-small", id:"inputEmail", placeholder:"名前"%><br/>
				<label>Profile image</label><br/>
					<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb" %><br/>
					<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form", fallback: "no_image.jpg"%><br />
				<label>Profile text </label><br/>
					<%= f.text_area :profile_text, autofocus: true, class:"imput-small", id:"inputEmail", placeholder:"自己紹介文" %> <br/>
				<%= f.submit "変更を保存", class: 'btn btn-primary'%>
			<% end %>

		</div>
	</div>
</div>

app/views/users/show.html.erb
<!doctype html>
<html>
<head>
	<meta charset="UTF-8">
</head>
<!-- ユーザー個人情報 -->
<body>
	<!-- フラッシュメッセージ -->
	<% if flash[:notice] %>
	<p id="notice"><%= flash[:notice] %></p>
	<% end %>
	<!-- ページの中身 -->
	<div class="container">
		<div class="row">
			<!-- ユーザー情報（共通テンプレート）  -->
			<div class="col-xs-3">
				<section class="">
					<h3> <%= @user.name %>'s Profile </h3>
					<img><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "img-circle pull-left profile-thumb" ,fallback: "no_image.jpg"%></img> <br/>
					<table class="table table-stripped">
						<tr><th> name </th>
							<th><%= @user.name %></th>
						</tr>
						<tr><th> introduction </th>
							<th><%= @user.profile_text %></th>
						</tr>
					</table>
				</section>
				<section class="new-book">
					<p class="headline-create-new-post"> create new post </p>
					<%= form_for(@newpost) do |f| %>
					<h4> title </h4>
					<%= f.text_field :title, class: "input-xlarge" %>
					<h4> impression </h4>
					<%= f.text_area :impression, :size=> "26x5" %><br />
					<%= f.submit 'create!', class: 'btn btn-primary col-xs-12'%>
					<% end %>
				</section>
			</div>
			<!-- 投稿内容一覧 -->
			<div class="col-xs-9">
				<section class="contents">
					<h3><%= @user.name %> 's  Posts </h3>
					<table class="table table-stripped">
						<tr align="left">
							<th> title </th>
							<th> impression </th>
							<th></th>
						</tr>
						<% @post.each do |post| %>
						<tr align="left">
							<td> <%= link_to post.title, booker_path(post) %> </td>
							<td> <%= link_to post.impression, booker_path(post) %> </td>
							<td>
								<%= link_to "詳しく見る", booker_path(post), class: 'btn btn-primary' %>
								<% if @user.id == current_user.id %>
								<%= link_to "編集", edit_booker_path(post), class: 'btn btn-info' %>
								<%= link_to "削除", booker_path(post), method: :delete, data: {confirm: '本当に削除してよろしいですか?'} , class: 'btn btn-danger' %>
								<% end %>
							</td>
						</tr>
						<% end %>
					</table>
					<%= paginate @post, class: "pagenate" %>
				</section>
			</div>
		</div>
	</div>
</body>
</html>

app/views/users/user.html.erb
<!doctype html>
<html>
<head>
	<meta charset="UTF-8">
</head>
<body>
	<div class="container">
		<div class="row">
			<!-- ユーザー情報（共通テンプレート） -->
			<%= render 'users/list', newpost: @newpost %>
			<!-- 投稿内容一覧 -->
			<div class="col-xs-9">
				<section class="contents">
					<h3>all users</h3>
					<table class="table table-stripped">
						<tr align="left">
							<th> profile image </th>
							<th> name </th>
							<th> <th>
							</tr>
							<% @user.each do |user| %>
							<tr align="left">
								<td> <%= attachment_image_tag user, :profile_image, :fill, 45, 45, class: "img-square pull-left profile-thumb", fallback: "no_image.jpg" %> </td>
								<td> <%= link_to user.name, user_path(user) %> </td>
								<td> <%= link_to "このユーザーの投稿を見る", user_path(user) ,class: 'btn btn-info'%> </td>
							</tr>
							<% end %>
						</table>
					</section>
				</div>
			</div>
		</div>
	</body>
	</html>